version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: UMaTLMS.API/Dockerfile
    ports:
      - "8083:83"
    depends_on:
      - phoenix-db
      
  phoenix-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=passMe%23tayeuaj
      - MSSQL_PID=Express
      - MSSQL_AUTHENTICATION=SqlPassword
    ports:
      - "1434:1433"
    volumes:
      - zomujo-data:/var/opt/mssql

volumes:
  zomujo-data:
