// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UMaTLMS.Infrastructure.Persistence;

#nullable disable

namespace UMaTLMS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230619120637_Lecture_PreferredRoom")]
    partial class Lecture_PreferredRoom
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LectureSubClassGroup", b =>
                {
                    b.Property<int>("LecturesId")
                        .HasColumnType("int");

                    b.Property<int>("SubClassGroupsId")
                        .HasColumnType("int");

                    b.HasKey("LecturesId", "SubClassGroupsId");

                    b.HasIndex("SubClassGroupsId");

                    b.ToTable("LectureSubClassGroup");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.ClassGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumOfSubClasses")
                        .HasColumnType("int");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.Property<int>("UmatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ClassGroups");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.ClassRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsLab")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.IncomingCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseCategory")
                        .HasColumnType("int");

                    b.Property<int>("CourseGroup")
                        .HasColumnType("int");

                    b.Property<string>("CourseId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseType")
                        .HasColumnType("int");

                    b.Property<int>("Credit")
                        .HasColumnType("int");

                    b.Property<int?>("FirstExaminerStaffId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PracticalHours")
                        .HasColumnType("int");

                    b.Property<string>("ProgrammeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProgrammeId")
                        .HasColumnType("int");

                    b.Property<int?>("SecondExaminerStaffId")
                        .HasColumnType("int");

                    b.Property<int>("TeachingHours")
                        .HasColumnType("int");

                    b.Property<int?>("UmatId")
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.Property<int?>("YearGroup")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("IncomingCourses");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.Lecture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<bool>("IsPractical")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVLE")
                        .HasColumnType("bit");

                    b.Property<int>("LecturerId")
                        .HasColumnType("int");

                    b.Property<int?>("OnlineLectureScheduleId")
                        .HasColumnType("int");

                    b.Property<int?>("PreferredRoom")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("LecturerId");

                    b.HasIndex("OnlineLectureScheduleId");

                    b.ToTable("Lectures");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.LectureSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DayOfWeek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FirstLectureId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int?>("SecondLectureId")
                        .HasColumnType("int");

                    b.Property<string>("TimePeriod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FirstLectureId");

                    b.HasIndex("RoomId");

                    b.HasIndex("SecondLectureId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.Lecturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UmatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.OnlineLectureSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DayOfWeek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimePeriod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OnlineSchedules");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOccurred")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateProcessed")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.SubClassGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("SubClassGroups");
                });

            modelBuilder.Entity("LectureSubClassGroup", b =>
                {
                    b.HasOne("UMaTLMS.Core.Entities.Lecture", null)
                        .WithMany()
                        .HasForeignKey("LecturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UMaTLMS.Core.Entities.SubClassGroup", null)
                        .WithMany()
                        .HasForeignKey("SubClassGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.ClassGroup", b =>
                {
                    b.OwnsOne("UMaTLMS.SharedKernel.Audit", "Audit", b1 =>
                        {
                            b1.Property<int>("ClassGroupId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 6, 19, 12, 6, 36, 607, DateTimeKind.Utc).AddTicks(5584));

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 6, 19, 12, 6, 36, 607, DateTimeKind.Utc).AddTicks(8837));

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.HasKey("ClassGroupId");

                            b1.ToTable("ClassGroups");

                            b1.WithOwner()
                                .HasForeignKey("ClassGroupId");
                        });

                    b.Navigation("Audit");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.ClassRoom", b =>
                {
                    b.OwnsOne("UMaTLMS.SharedKernel.Audit", "Audit", b1 =>
                        {
                            b1.Property<int>("ClassRoomId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 6, 19, 12, 6, 36, 754, DateTimeKind.Utc).AddTicks(319));

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 6, 19, 12, 6, 36, 754, DateTimeKind.Utc).AddTicks(2935));

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.HasKey("ClassRoomId");

                            b1.ToTable("Rooms");

                            b1.WithOwner()
                                .HasForeignKey("ClassRoomId");
                        });

                    b.Navigation("Audit");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.IncomingCourse", b =>
                {
                    b.OwnsOne("UMaTLMS.Core.Contracts.AcademicPeriodResponse", "AcademicPeriod", b1 =>
                        {
                            b1.Property<int>("IncomingCourseId")
                                .HasColumnType("int");

                            b1.Property<string>("AcademicYear")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("LowerYear")
                                .HasColumnType("int");

                            b1.Property<int>("Semester")
                                .HasColumnType("int");

                            b1.Property<int>("UpperYear")
                                .HasColumnType("int");

                            b1.HasKey("IncomingCourseId");

                            b1.ToTable("IncomingCourses");

                            b1.WithOwner()
                                .HasForeignKey("IncomingCourseId");
                        });

                    b.OwnsOne("UMaTLMS.SharedKernel.Audit", "Audit", b1 =>
                        {
                            b1.Property<int>("IncomingCourseId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 6, 19, 12, 6, 36, 640, DateTimeKind.Utc).AddTicks(6185));

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 6, 19, 12, 6, 36, 640, DateTimeKind.Utc).AddTicks(9409));

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.HasKey("IncomingCourseId");

                            b1.ToTable("IncomingCourses");

                            b1.WithOwner()
                                .HasForeignKey("IncomingCourseId");
                        });

                    b.Navigation("AcademicPeriod")
                        .IsRequired();

                    b.Navigation("Audit");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.Lecture", b =>
                {
                    b.HasOne("UMaTLMS.Core.Entities.IncomingCourse", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UMaTLMS.Core.Entities.Lecturer", "Lecturer")
                        .WithMany()
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UMaTLMS.Core.Entities.OnlineLectureSchedule", "OnlineLectureSchedule")
                        .WithMany("Lectures")
                        .HasForeignKey("OnlineLectureScheduleId");

                    b.OwnsOne("UMaTLMS.SharedKernel.Audit", "Audit", b1 =>
                        {
                            b1.Property<int>("LectureId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 6, 19, 12, 6, 36, 676, DateTimeKind.Utc).AddTicks(7896));

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 6, 19, 12, 6, 36, 677, DateTimeKind.Utc).AddTicks(146));

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.HasKey("LectureId");

                            b1.ToTable("Lectures");

                            b1.WithOwner()
                                .HasForeignKey("LectureId");
                        });

                    b.Navigation("Audit");

                    b.Navigation("Course");

                    b.Navigation("Lecturer");

                    b.Navigation("OnlineLectureSchedule");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.LectureSchedule", b =>
                {
                    b.HasOne("UMaTLMS.Core.Entities.Lecture", "FirstLecture")
                        .WithMany()
                        .HasForeignKey("FirstLectureId");

                    b.HasOne("UMaTLMS.Core.Entities.ClassRoom", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UMaTLMS.Core.Entities.Lecture", "SecondLecture")
                        .WithMany()
                        .HasForeignKey("SecondLectureId");

                    b.OwnsOne("UMaTLMS.SharedKernel.Audit", "Audit", b1 =>
                        {
                            b1.Property<int>("LectureScheduleId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 6, 19, 12, 6, 36, 723, DateTimeKind.Utc).AddTicks(1631));

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 6, 19, 12, 6, 36, 723, DateTimeKind.Utc).AddTicks(4953));

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.HasKey("LectureScheduleId");

                            b1.ToTable("Schedules");

                            b1.WithOwner()
                                .HasForeignKey("LectureScheduleId");
                        });

                    b.Navigation("Audit");

                    b.Navigation("FirstLecture");

                    b.Navigation("Room");

                    b.Navigation("SecondLecture");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.Lecturer", b =>
                {
                    b.OwnsOne("UMaTLMS.SharedKernel.Audit", "Audit", b1 =>
                        {
                            b1.Property<int>("LecturerId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 6, 19, 12, 6, 36, 706, DateTimeKind.Utc).AddTicks(9082));

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 6, 19, 12, 6, 36, 707, DateTimeKind.Utc).AddTicks(1381));

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.HasKey("LecturerId");

                            b1.ToTable("Lecturers");

                            b1.WithOwner()
                                .HasForeignKey("LecturerId");
                        });

                    b.Navigation("Audit");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.OnlineLectureSchedule", b =>
                {
                    b.OwnsOne("UMaTLMS.SharedKernel.Audit", "Audit", b1 =>
                        {
                            b1.Property<int>("OnlineLectureScheduleId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 6, 19, 12, 6, 36, 740, DateTimeKind.Utc).AddTicks(290));

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 6, 19, 12, 6, 36, 740, DateTimeKind.Utc).AddTicks(3888));

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.HasKey("OnlineLectureScheduleId");

                            b1.ToTable("OnlineSchedules");

                            b1.WithOwner()
                                .HasForeignKey("OnlineLectureScheduleId");
                        });

                    b.Navigation("Audit");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.SubClassGroup", b =>
                {
                    b.HasOne("UMaTLMS.Core.Entities.ClassGroup", "Group")
                        .WithMany("SubClassGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("UMaTLMS.SharedKernel.Audit", "Audit", b1 =>
                        {
                            b1.Property<int>("SubClassGroupId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 6, 19, 12, 6, 36, 773, DateTimeKind.Utc).AddTicks(1486));

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 6, 19, 12, 6, 36, 774, DateTimeKind.Utc).AddTicks(54));

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.HasKey("SubClassGroupId");

                            b1.ToTable("SubClassGroups");

                            b1.WithOwner()
                                .HasForeignKey("SubClassGroupId");
                        });

                    b.Navigation("Audit");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.ClassGroup", b =>
                {
                    b.Navigation("SubClassGroups");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.OnlineLectureSchedule", b =>
                {
                    b.Navigation("Lectures");
                });
#pragma warning restore 612, 618
        }
    }
}
