// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UMaTLMS.Infrastructure.Persistence;

#nullable disable

namespace UMaTLMS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExamsScheduleLecturer", b =>
                {
                    b.Property<int>("ExamsSchedulesId")
                        .HasColumnType("int");

                    b.Property<int>("InvigilatorsId")
                        .HasColumnType("int");

                    b.HasKey("ExamsSchedulesId", "InvigilatorsId");

                    b.HasIndex("InvigilatorsId");

                    b.ToTable("ExamsScheduleLecturer");
                });

            modelBuilder.Entity("ExamsScheduleSubClassGroup", b =>
                {
                    b.Property<int>("ExamsSchedulesId")
                        .HasColumnType("int");

                    b.Property<int>("SubClassGroupsId")
                        .HasColumnType("int");

                    b.HasKey("ExamsSchedulesId", "SubClassGroupsId");

                    b.HasIndex("SubClassGroupsId");

                    b.ToTable("ExamsScheduleSubClassGroup");
                });

            modelBuilder.Entity("LectureSubClassGroup", b =>
                {
                    b.Property<int>("LecturesId")
                        .HasColumnType("int");

                    b.Property<int>("SubClassGroupsId")
                        .HasColumnType("int");

                    b.HasKey("LecturesId", "SubClassGroupsId");

                    b.HasIndex("SubClassGroupsId");

                    b.ToTable("LectureSubClassGroup");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.ClassGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NumOfSubClasses")
                        .HasColumnType("int");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.Property<int>("UmatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("ClassGroups");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.ClassRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("IncludeInGeneralAssignment")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExaminationCenter")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLab")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.Constraint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("LecturerId")
                        .HasColumnType("int");

                    b.Property<string>("TimetableType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.ToTable("Constraints");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.ExamsSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfExam")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExamPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Examiner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExaminerId")
                        .HasColumnType("int");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("SerializedCourseCodes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("ExamsSchedules");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.IncomingCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CourseCategory")
                        .HasColumnType("int");

                    b.Property<int>("CourseGroup")
                        .HasColumnType("int");

                    b.Property<string>("CourseId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseType")
                        .HasColumnType("int");

                    b.Property<int>("Credit")
                        .HasColumnType("int");

                    b.Property<int?>("FirstExaminerStaffId")
                        .HasColumnType("int");

                    b.Property<bool>("HasPracticalExams")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExaminable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsToHaveWeeklyLectureSchedule")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PracticalHours")
                        .HasColumnType("int");

                    b.Property<string>("ProgrammeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProgrammeId")
                        .HasColumnType("int");

                    b.Property<int?>("SecondExaminerStaffId")
                        .HasColumnType("int");

                    b.Property<int>("TeachingHours")
                        .HasColumnType("int");

                    b.Property<int?>("UmatId")
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.Property<int?>("YearGroup")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("Name");

                    b.ToTable("IncomingCourses");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.Lecture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<bool>("IsPractical")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVLE")
                        .HasColumnType("bit");

                    b.Property<int>("LecturerId")
                        .HasColumnType("int");

                    b.Property<int?>("OnlineLectureScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("PreferredRoom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("LecturerId");

                    b.HasIndex("OnlineLectureScheduleId");

                    b.ToTable("Lectures");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.LectureSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DayOfWeek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FirstLectureId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int?>("SecondLectureId")
                        .HasColumnType("int");

                    b.Property<string>("TimePeriod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FirstLectureId");

                    b.HasIndex("RoomId");

                    b.HasIndex("SecondLectureId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.Lecturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TitledName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UmatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("UmatId");

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.OnlineLectureSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DayOfWeek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimePeriod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OnlineSchedules");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOccurred")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateProcessed")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.Preference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("LectureId")
                        .HasColumnType("int");

                    b.Property<int?>("LecturerId")
                        .HasColumnType("int");

                    b.Property<string>("TimetableType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("LectureId");

                    b.HasIndex("LecturerId");

                    b.ToTable("Preferences");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.SubClassGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("Name");

                    b.ToTable("SubClassGroups");
                });

            modelBuilder.Entity("ExamsScheduleLecturer", b =>
                {
                    b.HasOne("UMaTLMS.Core.Entities.ExamsSchedule", null)
                        .WithMany()
                        .HasForeignKey("ExamsSchedulesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UMaTLMS.Core.Entities.Lecturer", null)
                        .WithMany()
                        .HasForeignKey("InvigilatorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExamsScheduleSubClassGroup", b =>
                {
                    b.HasOne("UMaTLMS.Core.Entities.ExamsSchedule", null)
                        .WithMany()
                        .HasForeignKey("ExamsSchedulesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UMaTLMS.Core.Entities.SubClassGroup", null)
                        .WithMany()
                        .HasForeignKey("SubClassGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LectureSubClassGroup", b =>
                {
                    b.HasOne("UMaTLMS.Core.Entities.Lecture", null)
                        .WithMany()
                        .HasForeignKey("LecturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UMaTLMS.Core.Entities.SubClassGroup", null)
                        .WithMany()
                        .HasForeignKey("SubClassGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.ClassGroup", b =>
                {
                    b.OwnsOne("UMaTLMS.SharedKernel.Audit", "Audit", b1 =>
                        {
                            b1.Property<int>("ClassGroupId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 7, 27, 20, 53, 51, 846, DateTimeKind.Utc).AddTicks(1904));

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 7, 27, 20, 53, 51, 846, DateTimeKind.Utc).AddTicks(3121));

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.HasKey("ClassGroupId");

                            b1.ToTable("ClassGroups");

                            b1.WithOwner()
                                .HasForeignKey("ClassGroupId");
                        });

                    b.Navigation("Audit");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.ClassRoom", b =>
                {
                    b.OwnsOne("UMaTLMS.SharedKernel.Audit", "Audit", b1 =>
                        {
                            b1.Property<int>("ClassRoomId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 7, 27, 20, 53, 52, 37, DateTimeKind.Utc).AddTicks(5104));

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 7, 27, 20, 53, 52, 37, DateTimeKind.Utc).AddTicks(6811));

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.HasKey("ClassRoomId");

                            b1.ToTable("Rooms");

                            b1.WithOwner()
                                .HasForeignKey("ClassRoomId");
                        });

                    b.Navigation("Audit");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.Constraint", b =>
                {
                    b.HasOne("UMaTLMS.Core.Entities.Lecturer", "Lecturer")
                        .WithMany("Constraints")
                        .HasForeignKey("LecturerId");

                    b.OwnsOne("UMaTLMS.SharedKernel.Audit", "Audit", b1 =>
                        {
                            b1.Property<int>("ConstraintId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 7, 27, 20, 53, 51, 866, DateTimeKind.Utc).AddTicks(2534));

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 7, 27, 20, 53, 51, 866, DateTimeKind.Utc).AddTicks(5069));

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.HasKey("ConstraintId");

                            b1.ToTable("Constraints");

                            b1.WithOwner()
                                .HasForeignKey("ConstraintId");
                        });

                    b.Navigation("Audit");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.ExamsSchedule", b =>
                {
                    b.HasOne("UMaTLMS.Core.Entities.ClassRoom", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId");

                    b.OwnsOne("UMaTLMS.SharedKernel.Audit", "Audit", b1 =>
                        {
                            b1.Property<int>("ExamsScheduleId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 7, 27, 20, 53, 51, 941, DateTimeKind.Utc).AddTicks(7593));

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 7, 27, 20, 53, 51, 942, DateTimeKind.Utc).AddTicks(2222));

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.HasKey("ExamsScheduleId");

                            b1.ToTable("ExamsSchedules");

                            b1.WithOwner()
                                .HasForeignKey("ExamsScheduleId");
                        });

                    b.Navigation("Audit");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.IncomingCourse", b =>
                {
                    b.OwnsOne("UMaTLMS.Core.Contracts.AcademicPeriodResponse", "AcademicPeriod", b1 =>
                        {
                            b1.Property<int>("IncomingCourseId")
                                .HasColumnType("int");

                            b1.Property<string>("AcademicYear")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("LowerYear")
                                .HasColumnType("int");

                            b1.Property<int>("Semester")
                                .HasColumnType("int");

                            b1.Property<int>("UpperYear")
                                .HasColumnType("int");

                            b1.HasKey("IncomingCourseId");

                            b1.ToTable("IncomingCourses");

                            b1.WithOwner()
                                .HasForeignKey("IncomingCourseId");
                        });

                    b.OwnsOne("UMaTLMS.SharedKernel.Audit", "Audit", b1 =>
                        {
                            b1.Property<int>("IncomingCourseId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 7, 27, 20, 53, 51, 884, DateTimeKind.Utc).AddTicks(3520));

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 7, 27, 20, 53, 51, 885, DateTimeKind.Utc).AddTicks(563));

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.HasKey("IncomingCourseId");

                            b1.ToTable("IncomingCourses");

                            b1.WithOwner()
                                .HasForeignKey("IncomingCourseId");
                        });

                    b.Navigation("AcademicPeriod")
                        .IsRequired();

                    b.Navigation("Audit");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.Lecture", b =>
                {
                    b.HasOne("UMaTLMS.Core.Entities.IncomingCourse", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UMaTLMS.Core.Entities.Lecturer", "Lecturer")
                        .WithMany()
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UMaTLMS.Core.Entities.OnlineLectureSchedule", "OnlineLectureSchedule")
                        .WithMany("Lectures")
                        .HasForeignKey("OnlineLectureScheduleId");

                    b.OwnsOne("UMaTLMS.SharedKernel.Audit", "Audit", b1 =>
                        {
                            b1.Property<int>("LectureId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 7, 27, 20, 53, 51, 963, DateTimeKind.Utc).AddTicks(7090));

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 7, 27, 20, 53, 51, 964, DateTimeKind.Utc).AddTicks(223));

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.HasKey("LectureId");

                            b1.ToTable("Lectures");

                            b1.WithOwner()
                                .HasForeignKey("LectureId");
                        });

                    b.Navigation("Audit");

                    b.Navigation("Course");

                    b.Navigation("Lecturer");

                    b.Navigation("OnlineLectureSchedule");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.LectureSchedule", b =>
                {
                    b.HasOne("UMaTLMS.Core.Entities.Lecture", "FirstLecture")
                        .WithMany()
                        .HasForeignKey("FirstLectureId");

                    b.HasOne("UMaTLMS.Core.Entities.ClassRoom", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UMaTLMS.Core.Entities.Lecture", "SecondLecture")
                        .WithMany()
                        .HasForeignKey("SecondLectureId");

                    b.OwnsOne("UMaTLMS.SharedKernel.Audit", "Audit", b1 =>
                        {
                            b1.Property<int>("LectureScheduleId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 7, 27, 20, 53, 51, 997, DateTimeKind.Utc).AddTicks(5996));

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 7, 27, 20, 53, 51, 997, DateTimeKind.Utc).AddTicks(9206));

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.HasKey("LectureScheduleId");

                            b1.ToTable("Schedules");

                            b1.WithOwner()
                                .HasForeignKey("LectureScheduleId");
                        });

                    b.Navigation("Audit");

                    b.Navigation("FirstLecture");

                    b.Navigation("Room");

                    b.Navigation("SecondLecture");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.Lecturer", b =>
                {
                    b.OwnsOne("UMaTLMS.SharedKernel.Audit", "Audit", b1 =>
                        {
                            b1.Property<int>("LecturerId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 7, 27, 20, 53, 51, 981, DateTimeKind.Utc).AddTicks(2220));

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 7, 27, 20, 53, 51, 981, DateTimeKind.Utc).AddTicks(6008));

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.HasKey("LecturerId");

                            b1.ToTable("Lecturers");

                            b1.WithOwner()
                                .HasForeignKey("LecturerId");
                        });

                    b.Navigation("Audit");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.OnlineLectureSchedule", b =>
                {
                    b.OwnsOne("UMaTLMS.SharedKernel.Audit", "Audit", b1 =>
                        {
                            b1.Property<int>("OnlineLectureScheduleId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 7, 27, 20, 53, 52, 9, DateTimeKind.Utc).AddTicks(8943));

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 7, 27, 20, 53, 52, 10, DateTimeKind.Utc).AddTicks(1114));

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.HasKey("OnlineLectureScheduleId");

                            b1.ToTable("OnlineSchedules");

                            b1.WithOwner()
                                .HasForeignKey("OnlineLectureScheduleId");
                        });

                    b.Navigation("Audit");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.Preference", b =>
                {
                    b.HasOne("UMaTLMS.Core.Entities.IncomingCourse", "Course")
                        .WithMany("Preferences")
                        .HasForeignKey("CourseId");

                    b.HasOne("UMaTLMS.Core.Entities.Lecture", null)
                        .WithMany("Preferences")
                        .HasForeignKey("LectureId");

                    b.HasOne("UMaTLMS.Core.Entities.Lecturer", "Lecturer")
                        .WithMany("Preferences")
                        .HasForeignKey("LecturerId");

                    b.OwnsOne("UMaTLMS.SharedKernel.Audit", "Audit", b1 =>
                        {
                            b1.Property<int>("PreferenceId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 7, 27, 20, 53, 52, 23, DateTimeKind.Utc).AddTicks(6574));

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 7, 27, 20, 53, 52, 23, DateTimeKind.Utc).AddTicks(8918));

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.HasKey("PreferenceId");

                            b1.ToTable("Preferences");

                            b1.WithOwner()
                                .HasForeignKey("PreferenceId");
                        });

                    b.Navigation("Audit");

                    b.Navigation("Course");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.SubClassGroup", b =>
                {
                    b.HasOne("UMaTLMS.Core.Entities.ClassGroup", "Group")
                        .WithMany("SubClassGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("UMaTLMS.SharedKernel.Audit", "Audit", b1 =>
                        {
                            b1.Property<int>("SubClassGroupId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 7, 27, 20, 53, 52, 54, DateTimeKind.Utc).AddTicks(3947));

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValue(new DateTime(2023, 7, 27, 20, 53, 52, 54, DateTimeKind.Utc).AddTicks(5094));

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("admin");

                            b1.HasKey("SubClassGroupId");

                            b1.ToTable("SubClassGroups");

                            b1.WithOwner()
                                .HasForeignKey("SubClassGroupId");
                        });

                    b.Navigation("Audit");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.ClassGroup", b =>
                {
                    b.Navigation("SubClassGroups");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.IncomingCourse", b =>
                {
                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.Lecture", b =>
                {
                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.Lecturer", b =>
                {
                    b.Navigation("Constraints");

                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("UMaTLMS.Core.Entities.OnlineLectureSchedule", b =>
                {
                    b.Navigation("Lectures");
                });
#pragma warning restore 612, 618
        }
    }
}
